config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :meetups, only: [:index, :show, :create, :new] do
    resources :comments, only: :create
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post '/signup' => 'auth#signup'
      post '/login' => 'auth#login'
      post '/logout' => 'auth#logout'
      get '/meetups/:meetup_id' => 'meetups#show', as: :meetup
      get '/meetups' => 'meetups#index', as: :meetups
    end
  end

  root 'meetups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :meetup
end

app/models/meetup.rb
class Meetup < ApplicationRecord
  validates :title, presence: true
  has_many :members, through: :meetup_relationships, source: :user
  has_many :meetup_relationships
  has_many :comments
  belongs_to :user

end

app/models/meetup_relationship.rb
class MeetupRelationship < ApplicationRecord
  belongs_to :user
  belongs_to :meetup
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :meetup_relationships
  has_many :participated_meetups, through: :meetup_relationships, source: :meetup
  has_many :comments
  has_many :meetups
  before_create :generate_auth_token
  def generate_auth_token
    self.auth_token = Devise.friendly_token
  end

  def reset_auth_token
    generate_auth_token
    save
  end
end

app/controllers/api/v1/auth_controller.rb
class Api::V1::AuthController < ApiController
  before_action :authenticate_user!, only: [:logout]
  def signup
    user = User.new(email: params[:email], password: params[:password])

    if user.save
      render json: { user_id: user.id }, status: 200
    else
      render json: { message: 'Failed', errors: user.errors }, status: 400
    end
  end

  def login
    if params[:email] && params[:password]
      user = User.find_by_email(params[:email])
    end

    if user && user.valid_password?(params[:password])
      render json: { message: 'Ok',
                     auth_token: user.auth_token,
                     user_id: user.id }
    else
      render json: { message: 'wrong login information!' }, status: 401
    end
  end

  def logout
    current_user.reset_auth_token

    render json: { message: 'Ok' }
  end
end

app/controllers/api/v1/meetups_controller.rb
class Api::V1::MeetupsController < ApiController
  before_action :authenticate, only: [:show]
  def index
    @meetups = Meetup.all
    respond_to do |format|
      format.json
    end
  end

  def show
    @meetup = Meetup.find(params[:meetup_id])
    respond_to do |format|
      format.json
    end
  end

  protected

  def authenticate
    authenticate_token? || render_unauthorized
  end

  def authenticate_token?
    authenticate_with_http_token do |token, _options|
      User.find_by(auth_token: token)
    end
  end

  def render_unauthorized
    headers['WWW-Authenticate'] = 'Token realm="Episodes"'
    render json: 'bad crendentials', status: 401
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  #  protect_from_forgery with: :null_session
  #  # disable cookies (no set-cookies header in response)
  #  before_action :destroy_session
  #
  # # disable the CSRF token
  # skip_before_action :verify_authenticity_token
  #
  # def destroy_session
  #   request.session_options[:skip] = true
  # end
  before_action :authenticate_user_from_token!
  def authenticate_user_from_token!
    if params[:auth_token].present?
      user = User.find_by_auth_token(params[:auth_token])
      sign_in(user, store: false) if user
    end
  end

  def unauthorized!
    head 401
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @meetup = Meetup.find(params[:meetup_id])
    @comment = @meetup.comments.new(comments_params)
    @comment.user = current_user
    @comment.save!
    respond_to do |format|
      format.html { redirect_to @meetup }
      format.js
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @meetups = Meetup.all
  end

  def show
    @meetup = Meetup.find(params[:id])
  end

  def new
    @meetup = Meetup.new
  end

  def create
    @meetup = Meetup.new(meetup_params)
    @meetup.user = current_user
    if @meetup.save
      redirect_to meetups_path, notice: 'meetup up created!'
    else
      render :new, alert: 'failed'
    end
  end

  private

  def meetup_params
    params.require(:meetup).permit(:title, :description)
  end
end

app/views/comments/_comment.html.erb
<li>
  <span><%= comment.user.email %></span>
  <span class="date"><%= "at #{comment.id.ordinalize} floor" %></span>
  <span><%= time_ago_in_words(comment.created_at) %> ago</span>
  <p>
    <%= comment.content %>
  </p>
</li>

app/views/comments/create.js.erb
$('#comments').append("<%= j render @comment %>");
$('#comment_body').val("");

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 20px;">
    <p class="text-center">Copyright ©<%= Time.current.year %>
        <br> by <a href="https://github.com/cndaniel">cnDaniel</a>

    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Meetup</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("Login", new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to("Logout", destroy_user_session_path, method: :delete) %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "common/navbar" %>
      <div class="row">
        <%= yield %>
      </div>
      <%= render "common/footer" %>
    </div>
  </body>
</html>

app/views/meetups/index.html.erb
<div class= "col-md-12">
  <div class="meetup">
    <%= link_to 'create a meetpup', new_meetup_path, method: :get, class: :'btn btn-danger pull-right' %>
  </div>

  <table class='table'>
  <thead>
    <tr>
      <td>#</td>
      <td>Title</td>
      <td>Description</td>
    </tr>
  </theader>


  <tbody>
    <% @meetups.each do |meetup| %>
    <tr>
      <td>#</td>
      <td><%=link_to meetup.title, meetup_path(meetup) %></td>
      <td><%= meetup.description %></td>

    </tr>
    <% end %>
  </tbody>
</table>

</div>





</div>

app/views/meetups/new.html.erb
<div class= 'col-md-12'>
  <%= simple_form_for @meetup do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <div class="form-actions">
    <%= f.submit "Submit", disable_with: 'Submitting…', class:"btn btn-primary" %>
  </div>
  <% end %>

</div>

app/views/meetups/show.html.erb
<div class="col-md-12">


  <h2 style ='text-align: center'><%= @meetup.title %></h2>
  <p class="list-date">
    Listed on <%= @meetup.created_at %> by
    <%= @meetup.user.email%>
  </p>
  <p><%= @meetup.description %></p>




    <div class="text-center">
    <%= link_to "Comments", "#", id: "comments-link", class:'btn btn-info' %>


  <section id="comments-section">
    <ol id="comments">
      <%= render @meetup.comments %>
    </ol>
    <%= form_for [@meetup, @meetup.comments.new], remote: true do |f| %>
      <fieldset>

          <p>
            <%= f.text_area :content, rows: 2, cols: 60,
                            placeholder: "Write a comment..." %>
          </p>
          <p>
            <%= f.submit 'Post Comment', class: 'btn btn-lg btn-primary' %>
          </p>

      </fieldset>
    <% end %>
  </section>
    </div>


</div>